sudo: false

language: generic

addons:
  apt:
    packages:
      - llvm

cache:
  directories:
    - $HOME/.stack
    - $HOME/.local/bin
    - .stack-work/

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack install happy alex

script:
  - stack setup
  - stack build
  - stack install cabal-install
  - stack exec -- cabal update
  - stack test
  - stack clean
